require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec # if you are using RSpec for testing

AllCops:
  NewCops: enable
  DisplayCopNames: true
  TargetRubyVersion: 3.1.2
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'spec/dummy/**/*' # excluding dummy app in engine
    - 'vendor/**/*'

Rails:
  Enabled: true

# If using RSpec, enable these settings:
RSpec:
  Language:
    Describe:
      - describe
      - xdescribe
      - fdescribe
      - context
      - xcontext
      - fcontext

Layout/LineLength:
  Max: 120 # or your desired maximum line length

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'
  IgnoredMethods:
    - 'describe'
    - 'context'
    - 'included'

Metrics/MethodLength:
  Max: 15 # or your desired max method length
  Exclude:
    - 'migrations/**/*'

Metrics/AbcSize:
  Max: 20 # or your desired ABC size limit

Metrics/CyclomaticComplexity:
  Max: 7 # or your desired complexity

Metrics/PerceivedComplexity:
  Max: 8 # or your desired perceived complexity

Style/Documentation:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

# Any other specific rules or overrides for your code style go below.
